# All config options can be overwrote by ENV variables,
# For example: `Server.HTTPPort: 9331` the corresponding ENV variable can be set as: `export SERVER_HTTPPORT=9331`

App:
  Name: readygo
  PageSize: 20
  RuntimeRootPath: runtime/
  SuperAdminID: 1
  TimeFormat: "2006-01-02 15:04:05"

CORS:
  AllowOrigin: "*"
  AllowMethods: "OPTIONS, GET, POST, PUT, DELETE"

Gin:
  Mode: debug # debug or release

JWT:
  Secret:
  Expires: 24 # hours
  Issuer: readygo

Server:
  HTTPHost: 127.0.0.1
  HTTPPort: 9331
  ReadTimeout: 60 # seconds
  WriteTimeOut: 60 # seconds

Database:
  Type: SQLite # MySQL or SQLite
  Prefix: g_

MySQL:
  Host: 127.0.0.1
  Port: 3306
  User: root
  Password:
  Name: readygo
  Charset: utf8mb4
  MaxIdleConns: 10
  MaxOpenConns: 100
  ConnMaxLifetime: 3000 # seconds

SQLite:
  Name: db.sqlite

Redis:
  Enabled: 0
  Addr: 127.0.0.1:6379
  Password:
  DB: 0

Captcha:
  Enabled: 0
  Store: Memory # Redis or Memory
  Height: 40
  Width: 100
  Length: 6
  Prefix: captcha_
  Expires: 600 # seconds
